---
abstract: 'Mojo I18n with Locale::Wolowitz'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110580'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Wolowitz
requires:
  Locale::Wolowitz: 0
  Mojo::Base: 0
resources:
  bugtracker: https://github.com/gugod/Mojolicious-Plugin-Wolowitz/issues
  repository: git://github.com/gugod/Mojolicious-Plugin-Wolowitz.git
version: 1.0.1
